# Generated by Django 5.0.1 on 2024-02-03 15:51

import django.db.models.deletion
import test_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, validators=[test_app.models.isItemNameValid], verbose_name='Item Number')),
                ('description', models.CharField(max_length=250, null=True)),
                ('season', models.CharField(max_length=250, null=True, validators=[test_app.models.isSeasonValid])),
                ('proto', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/media/newItems')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('job_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_groups', to='test_app.jobgroup')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('operation_code', models.IntegerField()),
                ('note', models.TextField(blank=True, max_length=1500, null=True)),
                ('bundle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.bundlegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ElementLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('note', models.TextField(blank=True, max_length=1500, null=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.operationlib')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='OperationListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('operations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.operationlib')),
            ],
        ),
        migrations.CreateModel(
            name='ElementListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanding_name', models.CharField(blank=True, max_length=500, null=True)),
                ('nmt', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.elementlib')),
                ('listItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.operationlistitem')),
                ('options', models.ManyToManyField(blank=True, to='test_app.option')),
            ],
        ),
        migrations.CreateModel(
            name='TimeStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.elementlib')),
                ('options', models.ManyToManyField(blank=True, to='test_app.option')),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('options', models.ManyToManyField(blank=True, to='test_app.option')),
            ],
        ),
        migrations.AddField(
            model_name='elementlib',
            name='variables',
            field=models.ManyToManyField(blank=True, to='test_app.variables'),
        ),
        migrations.CreateModel(
            name='YourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.newitem')),
            ],
        ),
        migrations.AddField(
            model_name='operationlistitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.yourlist'),
        ),
    ]
