# Generated by Django 4.2.6 on 2024-01-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroup',
            name='image',
            field=models.ImageField(upload_to='jobGroup/'),
        ),
        migrations.AlterField(
            model_name='newitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newItems/'),
        ),
    ]
