# Generated by Django 4.2.6 on 2024-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlib',
            name='refStyle',
            field=models.ManyToManyField(blank=True, to='test_app.refstyle', verbose_name='Ref Style'),
        ),
    ]
