# Generated by Django 5.0.1 on 2024-02-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('operation_code', models.IntegerField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.operationlib')),
            ],
        ),
        migrations.AddField(
            model_name='operationlistitem',
            name='expanding_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_app.operationcode'),
        ),
    ]
