# Generated by Django 5.0.1 on 2024-03-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_operationlistitem_expanding_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobgroup',
            name='is_finished',
        ),
        migrations.CreateModel(
            name='BundleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.bundlegroup')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.yourlist')),
            ],
        ),
    ]
