# Generated by Django 5.0.1 on 2024-02-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_operationcode_operationlistitem_expanding_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlib',
            name='operation_code',
        ),
    ]
