# Generated by Django 4.2.6 on 2024-01-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0002_alter_operationlib_refstyle"),
    ]

    def reorder(apps, schema_editor):
        MyModel = apps.get_model("test_app", "ElementLib")
        for order, item in enumerate(MyModel.objects.all(), 1):
            item.my_order = order
            item.save(update_fields=["my_order"])

    operations = [
        migrations.AlterModelOptions(
            name="elementlib",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="elementlib",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
