# Generated by Django 4.2.6 on 2024-01-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_elementlib_options_elementlib_my_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlib',
            name='machine',
        ),
        migrations.AddField(
            model_name='elementlib',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='test_app.machine'),
            preserve_default=False,
        ),
    ]
