# Generated by Django 5.0.1 on 2024-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_operationlib_operation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlistitem',
            name='expanding_field',
        ),
        migrations.AddField(
            model_name='operationlib',
            name='operation_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
