# Generated by Django 4.2.6 on 2024-01-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_remove_operationlib_machine_elementlib_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementlib',
            name='machine',
        ),
    ]
