# Generated by Django 5.0.1 on 2024-03-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_jobstatus_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementlib',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='timestudy',
            name='elements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.elementlib', to_field='name'),
        ),
    ]
