# Generated by Django 5.0.1 on 2024-02-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_remove_operationlib_operation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationcode',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
