# Generated by Django 4.2.6 on 2024-01-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_test_testchild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testchild',
            name='test',
        ),
        migrations.AlterField(
            model_name='timestudy',
            name='elements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.elementlib'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestChild',
        ),
    ]
