# Generated by Django 5.0.1 on 2024-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_operationcode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlistitem',
            name='expanding_field',
        ),
        migrations.AddField(
            model_name='operationlib',
            name='job_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationlistitem',
            name='expanding_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='OperationCode',
        ),
    ]
