# Generated by Django 5.0.1 on 2024-03-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlegroup',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
