# Generated by Django 4.2.6 on 2024-01-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_remove_testchild_test_alter_timestudy_elements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='MachineType',
        ),
    ]
