# Generated by Django 5.0.1 on 2024-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_bundlegroup_name_alter_jobgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlib',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
