# Generated by Django 5.0.1 on 2024-03-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_alter_operationlib_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlistitem',
            name='operations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.operationlib', to_field='name'),
        ),
    ]
