# Generated by Django 5.0.1 on 2024-03-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_alter_operationlistitem_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlegroup',
            name='job_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_groups', to='test_app.jobgroup', to_field='name'),
        ),
    ]
