# Generated by Django 5.0.1 on 2024-03-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_alter_bundlegroup_job_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlib',
            name='bundle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.bundlegroup', to_field='name'),
        ),
    ]
